### ISSUE TITLE
Examples are not functioning as intended

### ISSUE THREAD

**Issue by modelarious** [hudsonbrendon/python-musixmatch#6]
I'm going through the examples trying to use the API for my purposes, but many of the provided examples do not have all the needed positional parameters.  

For example:

musixmatch.track_search(q_artist='twentyonepilots', page_size=10, page=1, s_track_rating='desc')

will throw a TypeError telling the user: "TypeError: track_search() missing 1 required positional argument: 'q_track'"

**Comment by jac0b-w** [comment]
Yeah it should be something like this:
`musixmatch.track_search(
    q_artist='Twenty One Pilots',
    q_track = "Ride",
    page_size=10,
    page=1,
    s_track_rating='desc',
    )`

**Comment by geraldspacelim** [comment]
hi @jac0b-w, this api is not working recently, it is returning {'message': {'header': {'status_code': 500, 'execute_time': 0.0043199062347412, 'exception_id': 2000}, 'body': ''}}

**Comment by hudsonbrendon** [comment]
Sorry, I'm already working on a PR that corrects this.

**Comment by AliAAgaming** [comment]
Ride
