### ISSUE TITLE
Example giving 403 on richsync api call

### ISSUE THREAD

**Issue by sharksforarms** [hudsonbrendon/python-musixmatch#8]
Getting a error 403 on the example `musixmatch.track_richsync_get(14201829)` any ideas?

**Comment by hudsonbrendon** [comment]
Sorry, I'm already working on a PR that corrects this.

**Comment by phanirithvij2000** [comment]
Can this be closed?

**Comment by emily2h** [comment]
Does this work yet or is this on Musixmatch's end?

**Comment by Feridinha** [comment]
I still get 403 when I try to call `musixmatch.track_richsync_get` . Do I need some kind of special api key to use this endpoint?
